org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
podcst.rustToolchain=stable
podcst.androidAbis=arm64-v8a,armeabi-v7a,x86_64

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
